config/routes.rb
  Rails.application.routes.draw do

  devise_for :admins
  resources :posts do
    resources :comments
  end


  root "pages#index"

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/clients', to: 'pages#portfolio'
  get '/expertise', to: 'pages#services'
  get '/posts', to: 'posts#index'

  post '/posts/new', to: 'posts#show'

  # Mailchimp
  post 'emailapi/subscribe' => 'emailapi#subscribe'
  # get 'emailapi/subscribe' => 'emailapi#subscribe' 





end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body,  presence: true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

  def show
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

end

app/controllers/emailapi_controller.rb
class EmailapiController < ApplicationController
  include EmailapiHelper

   skip_before_action :verify_authenticity_token


  def subscribe
    email = params[:email][:address]
    # respond_to do |format|
      if 
        is_a_valid_email?(email)
        @list_id = "a8d92e6f2e"
        gb = Gibbon::API.new

        gb.lists.subscribe({
          :id => @list_id,
          :email => {:email => email}
        })

        redirect_to(root_path, :flash => :success)
      else
        redirect_to(root_path, :flash => :error)





      #   format.json { render json: {msg: "Please check your supplied email to confirm subscription!" }}
      # else
      #   format.json { render json: {msg: "Invalid email" }}
      
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end

  def index
  end
end

app/controllers/posts_controller.rb
  class PostsController < ApplicationController
	# before_action :authenticate_admin!, except: [:index, :show]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new 
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emailapi_helper.rb
module EmailapiHelper

  def is_a_valid_email?(email)
    (email =~ /^(([A-Za-z0-9]*\.+*_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\+)|([A-Za-z0-9]+\+))*[A-Z‌​a-z0-9]+@{1}((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,4}$/i)
  end
end

app/views/comments/_comment.html.erb
<div class="comment-box clearfix">
<img src="assets/img/blog/blog-1.jpg" class="img-responsive" alt="">
	<span>by <%= comment.name %></span>
		<p><%= comment.body %></p>
		<p><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	<% if admin_signed_in? %>
	<p><%= link_to 'Delete', [comment.post, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %></p>
 	<% end %>
 	</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<div class="row">
    <div class="col-md-6">
      </br>
	    <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: 'Name' %><br>
    </div>
      <div class="col-md-6">
        </br>
        <input type="email" class="form-control" placeholder="Email"></br>
      </div>
	      <div class="col-md-12">
	        <br>
	        <%= f.text_area :body, class: "form-control", autofocus: true, placeholder: 'Message' %><br>
        </div>
	       <div class="col-md-12 text-right">
	        <%= f.submit 'Comment', class: "btn btn-lg theme-btn-color" %>
         </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thinkpr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400italic' rel='stylesheet' type='text/css'>
</head>
<body>
<header class="header-main">




      <% if current_admin %>
      <div class="top-bar">

                <div class="container">
                    <ul class="info list-inline pull-left hidden-xs">
                        <li><a href="#" class="hover-color"><i class="ion-ios-email-outline"></i> <%= current_admin.email %></a></li>
                        <li><i class="ion-iphone"></i> +91 (123) 456 78 90</li>
                    </ul>  
                    <div class="pull-right">
                        <ul class="info list-inline hidden-xs">
                            <li><!-- <a href="#" class="hover-color">Create an account?</a> --></li>
                            <li></i><%= link_to "Log out", destroy_admin_session_path, method: :delete %></li>
                        </ul>
                    </div>
                </div><!--container end-->
            </div><!--t
              
            <% end %> 
      </div>



            <div class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">thinkPR<!-- <img src="assets/img/logo-dark.png" class="img-responsive logo" alt=""> --></a>
                    </div>
                    <div class="navbar-collapse collapse">

                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <%= link_to "About", about_path %>
                            </li>
                            <li class="dropdown">
                                 <%= link_to "Expertise", expertise_path %>
                                <ul class="dropdown-menu">
                                    <li><a href="portfolio.html">Portfolio 3 col</a></li>
                                    <li><a href="portfolio-masonry.html">Portfolio Masonry</a></li>
                                    <li><a href="portfolio-full.html">Portfolio Full width</a></li>
                                    <li><a href="portfolio-full-boxed.html">Full width boxed</a></li>                            
                                    <li><a href="portfolio-single.html">Portfolio Single</a></li>
                                </ul>
                            </li>
                            <li class="">
                                <%= link_to "Clients", clients_path %>
                            </li>
                            <li class="">
                                <a href="#" class="dropdown-toggle js-activated" data-toggle="dropdown">Showroom</a>
                            </li>
                            <li class= "">
                                <%= link_to "Blog", posts_path %>
                              
                            </li>
                             <li class= "">
                               <%= link_to "Contact", contact_path %>
                                
                            </li>
                            <li class="social-nav"><a href="http://www.facebook.com/Thinkprdk"><i class="ion-social-facebook"></i></a></li>
                            <li class="social-nav"><a href="http://www.twitter.com/thinkprdk"><i class="ion-social-twitter"></i></a></li>
                            <li class="social-nav"><a href="http://www.linkedin.com/company/think-pr-denmark-"><i class="ion-social-linkedin"></i></a></li>
                        </ul>

                    </div><!--/.nav-collapse -->
                </div><!--/.container-->
            </div><!--navigation end-->

        </header><!--header main end-->


<!-- Mailchimp notifications -->

<!--         <div id="flash_messages"><%= flash_messages %></div>
 --><!-- End -->

<!-- Notification and alerts (devise) -->

      <% if notice || alert || flash_messages %>
         <div class="container-fluid" style="padding-left: 0px; padding-right: 0px; background-color:#222"> 
      <div class="col-md-12" style="height:58px">
        <div class="alert alert-success alert-dismissable">
          <span class="glyphicon glyphicon-certificate"></span>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
              ×</button>
              <%= notice %>
              <% end %>
              </div>
        
        <% if alert %>

        <div class="alert alert-danger alert-dismissable">
            <span class="glyphicon glyphicon-certificate"></span>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                ×</button>
                <%= alert %>
                <% end %>
                </div>

        <% if flash_messages %>

        <div class="alert alert-success alert-dismissable" id="">
            <span class="glyphicon glyphicon-certificate"></span>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                ×</button>
                <%= flash_messages %>
                <% end %>
                </div>

      </div>  

<!-- End notification and alerts -->

<%= yield %>
<!--  <div class="space-70"></div>
 --> <footer id="footer-option">
              <div class="container">
                <div class="row">
                    <div class="col-md-3 margin-btm-20">
                        <div class="footer-col">
                            <h3>Newsletter</h3>
                            <p class="margin-btm-20">
                                Keep up on our always evolving Future updates. Enter your e-mail and subscribe to our newsletter.
                            </p>


<!--Mailchimp integration-->
                           <%= form_tag('emailapi/subscribe', class: "input-group", method: "post", id: "subscribe", remote: "true", 'data-type' => :json) do -%>
                            <div class="form-group">
                               <%= email_field(:email, :address, {class: "form-control", id: "subscribe-email", placeholder: "Enter your email"})%>
                            </div>
                            <span class="input-group-btn">
                             <%= button_tag(type: 'submit', class: "btn theme-btn-color") do %> Go!
                             <% end %>
                             </span>
                           <% end %>
<!-- Mailchimp integration end -->

                        </div>
                    </div><!--footer col end-->



                    <div class="col-md-3 margin-btm-20">
                        <div class="footer-col margin-btm-20">
                            <h3>Latest tweet</h3>
                            <a href="#" class="tweet-ac hover-color">@rakesh_wd</a>
                            <div class="tweet-desc">
                                <i class="ion-social-twitter"></i>Bizwrap is right choice for your business project.its comes with new features and update in every month.
                            </div>
                            <a href="#" class="hover-color tweet-day">50 min ago</a>
                            <hr>
                        </div>
                        <div class="footer-col">
                            <a href="#" class="tweet-ac hover-color">@rakesh_wd</a>
                            <div class="tweet-desc">
                                <i class="ion-social-twitter"></i>Bizwrap is right choice for your business project.its comes with new features and update in every month.
                            </div>
                            <a href="#" class="hover-color tweet-day">1 day ago</a>
                        </div>
                    </div><!--footer col end-->
                    <div class="col-md-3 margin-btm-20">
                        <div class="footer-col margin-btm-20">
                            <h3>Follow us</h3>
                            <ul class=" list-inline social-btn">
                                <li><a href="http://www.facebook.com/Thinkprdk"><i class="ion-social-facebook" data-toggle="tooltip" data-placement="top" title="" data-original-title="Like On Facebook"></i></a></li>
                                <li><a href="http://www.twitter.com/thinkprdk"><i class="ion-social-twitter" data-toggle="tooltip" data-placement="top" title="" data-original-title="Follow On twitter"></i></a></li>
                                <li><a href="http://www.linkedin.com/company/think-pr-denmark-"><i class="ion-social-linkedin" data-toggle="tooltip" data-placement="top" title="" data-original-title="Connect On LinkedIn"></i></a></li>
                            </ul>
                        </div> 
                    </div><!--footer col end-->
                    <div class="col-md-3 margin-btm-20">
                        <div class="footer-col">
                            <h3>contact info</h3>
                            <p><i class="ion-home"></i> Kronprinsensgade 5, 2. sal, 
1114 København K</p>
                            <p><i class="ion-iphone"></i> [+45] 33 14 00 00</p>
                            <p><i class="ion-email"></i> info@thinkpr.dk</p>
                        </div>

                    </div><!--footer col end-->
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    <div class="row">
                        <div class="col-md-1 footer-logo">
                            <a href="index.html">
                                <img src="assets/img/logo-white.png" alt="">
                            </a>
                        </div>
                        <div class="col-md-5">
                            <p>&copy; copyright 2015. developed by <a href="http://www.blackboxdev.co" style="color:#777">blackbox dev.</p>
                        </div>
                        <div class="col-md-6 ">
                            <ul class="list-inline footer-nav">
                                <li><a href="/about">About</a></li>
                                <li><a href="/expertise">Expertise</a></li>
                                <li><a href="/clients">Clients</a></li>
                                <li><a href="/">Showroom</a></li>
                                <li><a href="/posts">Blog</a></li>
                                <li><a href="/contact">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer><!--footer main end-->


</body>
</html>

app/views/posts/_form.html.erb
 <%= form_for @post, html: { multipart: true } do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>


	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_field :body %><br>
	<br>
	<%= f.label :image %><br>
	<%= f.file_field :image %><br>
	<br>
	<%= f.submit "Publish", class: "btn btn-large" %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div style="float:right; margin-top: 25px; margin-right: 60px">
        <!-- <% if admin_signed_in? %> -->
            
              <%= link_to "Create New Post", new_post_path, class: "btn btn-default", style: "background-color:#1abc9c; color:#f5f5f5" %></button>
            
        <!--<%end%>-->
        </div>

       <section id="content-region-3" class="padding-40 page-tree-bg">
            <div class="container">
                <h3 class="page-tree-text">
                    Blog
                </h3>
            </div>
        </section><!--page-tree end here-->
        <div class="space-70"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                <% @posts.each do |post| %>

                    <div class="blog-post-section">
                        <div class="blog-post-img">
                            <%= image_tag post.image.url(:medium), class: "img-responsive" %>
                        </div>
                        <div class="blog-post-header">
                            <h3><a href="" class="hover-color"><%= post.title %></a></h3>
                        </div>
                             <div class="blog-post-info">
                            <span><a href="#" class="hover-color"><%=(post.created_at) %> | <%= post.comments.count %> Comments</span>
                        </div>
                        <div class="blog-post-detail">
                           <p><%= post.body %></p>
                        </div>
                        <% end %>

                       
                    </div><!--blog post section end-->
                   
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="pagination">
                                <li><a href="#">&laquo;</a></li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li><a href="#">&raquo;</a></li>
                            </ul>
                        </div>
                    </div>


                </div><!--blog content-->
                <div class="col-md-4">
                    <!-- <div class="sidebar-box">
                        <div class="widget-search">
                            <form class="search-form">
                                <input type="text" class="form-control" placeholder="search here...">
                                <i class="ion-search" data-toggle="tooltip" data-placement="top" title="" data-original-title="hit enter to search"></i>
                            </form>
                        </div>
                    </div><!sidebar-box--><!--  <hr> -->
                    <!-- <div class="sidebar-box">
                        <h4>categories</h4>
                        <ul class="cat-list">
                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="" data-original-title="10" class="hover-color">Sports</a></li>
                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="" data-original-title="6" class="hover-color">Management</a></li>
                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="" data-original-title="8" class="hover-color">Music</a></li>
                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="" data-original-title="14" class="hover-color">Product</a></li>
                        </ul>
                    </div><hr> -->
                    <div class="sidebar-box">
                        <h4>Text widget</h4>
                        <p>
                            Doloreiur quia commolu ptatemp dolupta oreprerum tibusam eumenis et consent accullignis dentibea autem inisita.
                        </p>
                    </div><hr>
                    <div class="sidebar-box">
                        <h4>recent post</h4>
                        <div class="recent">
                            <span>
                                <img src="assets/img/blog/blog-1.jpg" class="img-responsive" alt="">
                            </span>
                            <p><a href="#" class="hover-color">There are many  embarrassing hidden in the middle of text.</a></p>
                            <span class="recent-date">On 27 may in office.</span>
                        </div>
                        <div class="recent">
                            <span>
                                <img src="assets/img/blog/blog-2.jpg" class="img-responsive" alt="">
                            </span>
                            <p><a href="#" class="hover-color">There are many  embarrassing hidden in the middle of text.</a></p>
                            <span class="recent-date">On 27 may in office.</span>
                        </div>
                        <div class="recent">
                            <span>
                                <img src="assets/img/blog/blog-3.jpg" class="img-responsive" alt="">
                            </span>
                            <p><a href="#" class="hover-color">There are many  embarrassing hidden in the middle of text.</a></p>
                            <span class="recent-date">On 27 may in office.</span>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <hr>
                    <div class="sidebar-box">
                        <h4>Elsewhere</h4>
                        <ul class=" list-inline social-btn">
                          <li><a href="http://www.facebook.com/Thinkprdk"><i class="ion-social-facebook" data-toggle="tooltip" data-placement="top" title="" data-original-title="Like On Facebook"></i></a></li>
                            <li><a href="http://www.twitter.com/thinkprdk"><i class="ion-social-twitter" data-toggle="tooltip" data-placement="top" title="" data-original-title="Follow On twitter"></i></a></li>
                            <li><a href="http://www.linkedin.com/company/think-pr-denmark-"><i class="ion-social-linkedin" data-toggle="tooltip" data-placement="top" title="" data-original-title="Connect On LinkedIn"></i></a></li>
                            
                        </ul>
                    </div><hr>
                    <div class="sidebar-box">
                      <div style="float:left; margin-top: 10px;">
        <!-- <% if admin_signed_in? %> -->
            
              <%= link_to "Create New Post", new_post_path, class: "btn btn-large", style: "background-color:#1abc9c; color:#f5f5f5" %></button>
            
        <!--<%end%>-->
        </div>

                    </div>
                </div><!--sideabr blog end -->
            </div>

        </div><!--blog sidebar page content end here-->
                       <div class="space-50"></div>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>